Revert TfidMatrix logic, extend and improve documentation
raccoongang/edx_telegram_bot pull request #2
Opened 2017-06-14 11:03 UTC by DmytryiStriletskyi

2017-06-14 11:11 UTC, z4y4ts requested changes

2017-06-14 11:11 UTC, z4y4ts commented on README.md
> +3. Add telegram `id` and telegram `username` (optional move, it\`s can be empty - `''`).
`it can be empty`

2017-06-14 11:11 UTC, z4y4ts commented on README.md
> +If you don`t know telegram id and nickname, just go ahead and log this there
log this -> log it

2017-06-14 11:11 UTC, z4y4ts commented on README.md
> +Pay attention to key `from`, there`s all data you need:
there's -> here's

2017-06-14 11:11 UTC, z4y4ts commented on README.md
> +3. Add telegram `id` and telegram `username` (optional move, it\'s can be empty - `''`).
it can be empty

2017-06-14 11:11 UTC, z4y4ts commented on README.md
> +If you don't know telegram id and nickname, just go ahead and log this there
log this -> log it

2017-06-14 11:11 UTC, z4y4ts commented on README.md
> +Update {'message': {'migrate_to_chat_id': 0, 'delete_chat_photo': False, 'new_chat_photo': [],
Use `pprint.pprint`

2017-06-14 11:11 UTC, z4y4ts commented on README.md
>      print update.message
Use `pprint.pprint`

2017-06-14 11:14 UTC, DmytryiStriletskyi commented on README.md
> +Update {'message': {'migrate_to_chat_id': 0, 'delete_chat_photo': False, 'new_chat_photo': [],
@z4y4ts, why i need to use `pprint.pprint`, that needed additional `import pprint`?
Dev just gonna get data one time.

2017-06-14 11:14 UTC, DmytryiStriletskyi commented on README.md
>      print update.message
The same below.

2017-06-14 11:15 UTC, DmytryiStriletskyi commented on README.md
> +If you don't know telegram id and nickname, just go ahead and log this there
Done.

2017-06-14 11:15 UTC, DmytryiStriletskyi commented on README.md
> +3. Add telegram `id` and telegram `username` (optional move, it\'s can be empty - `''`).
Done.

2017-06-14 11:15 UTC, DmytryiStriletskyi commented on README.md
> +If you don`t know telegram id and nickname, just go ahead and log this there
Done.

2017-06-14 11:15 UTC, DmytryiStriletskyi commented on README.md
> +3. Add telegram `id` and telegram `username` (optional move, it\`s can be empty - `''`).
Done.

2017-06-14 13:31 UTC, idegtiarov requested changes

2017-06-14 13:31 UTC, idegtiarov commented on README.md
> +3. Add telegram `id` and telegram `username` (optional move, it can be empty - `''`).
`s/(optional move, it can be empty - `''`)/(optional)/` --- will be fair enough.

2017-06-14 13:31 UTC, idegtiarov commented on README.md
> +`update.message` example of print:
It would be better to change with: `s/print/output/`

2017-06-14 13:31 UTC, idegtiarov commented on README.md
>      print update.message
It should be mentioned that `print` won't be logged if the app is running under supervisor.

2017-06-14 13:41 UTC, DmytryiStriletskyi commented on README.md
>      print update.message
Done.

2017-06-14 13:42 UTC, DmytryiStriletskyi commented on README.md
> +`update.message` example of print:
Done.

2017-06-14 13:44 UTC, DmytryiStriletskyi commented on README.md
> +3. Add telegram `id` and telegram `username` (optional move, it can be empty - `''`).
Done.

2017-06-14 13:53 UTC, idegtiarov approved these changes
Thanks for the fast fixing.

2017-06-20 10:27 UTC, z4y4ts approved these changes
Looks good to me

2017-06-20 12:17 UTC, merged